using System;
using System.Linq;
using Grasshopper.Kernel;
using DB = Autodesk.Revit.DB;

namespace RhinoInside.Revit.GH.Components
{
  public class AnalyzeCurtainGrid : AnalysisComponent
  {
    public override Guid ComponentGuid => new Guid("D7B5C58E-8EDC-40C5-9BF8-078642090264");
    public override GH_Exposure Exposure => GH_Exposure.septenary;
    protected override string IconTag => "ACG";

    public AnalyzeCurtainGrid() : base(
      name: "Analyze Curtain Grid",
      nickname: "A-CG",
      description: "Analyze given curtain grid",
      category: "Revit",
      subCategory: "Wall"
    )
    {
    }

    protected override void RegisterInputParams(GH_InputParamManager manager)
    {
      manager.AddParameter(
        param: new Parameters.DataObject<DB.CurtainGrid>(),
        name: "Curtain Grid",
        nickname: "CG",
        description: "Curtain Grid",
        access: GH_ParamAccess.item
        );
    }

    protected override void RegisterOutputParams(GH_OutputParamManager manager)
    {
      // grid cells
      manager.AddParameter(
        param: new Parameters.DataObject<DB.CurtainCell>(),
        name: "Cells",
        nickname: "C",
        description: "Grid cells generated by the given Curtain Grid",
        access: GH_ParamAccess.item
        );

      // grid parts
      manager.AddParameter(
        param: new Parameters.Mullion(),
        name: "Mullions",
        nickname: "M",
        description: "Grid mullion elements generated by the given Curtain Grid",
        access: GH_ParamAccess.item
        );
      manager.AddParameter(
        param: new Parameters.GraphicalElement(), // may be Panel or Wall
        name: "Panels",
        nickname: "P",
        description: "Grid panel elements generated by the given Curtain Grid",
        access: GH_ParamAccess.item
        );

      // grid lines
      // U
      manager.AddParameter(
        param: new Parameters.CurtainGridLine(),
        name: "Vertical Lines",
        nickname: "VL",
        description: "Grid line elements generated by the given Curtain Grid along the U axis",
        access: GH_ParamAccess.item
        );
      // U grid properties
      manager.AddNumberParameter(
        name: "Vertical Angle",
        nickname: "VA",
        description: "The angle for the U grid line pattern of the given curtain grid",
        access: GH_ParamAccess.item
        );
      manager.AddParameter(
        param: new Parameters.Param_Enum<Types.CurtainGridAlignType>(),
        name: "Vertical Justification",
        nickname: "VJ",
        description: "The alignment type for the U grid line pattern of the given curtain grid",
        access: GH_ParamAccess.item
        );
      manager.AddNumberParameter(
        name: "Vertical Offset",
        nickname: "VO",
        description: "The offset for the U grid line pattern of the given curtain grid",
        access: GH_ParamAccess.item
        );

      // V
      manager.AddParameter(
        param: new Parameters.CurtainGridLine(),
        name: "Horizontal Lines",
        nickname: "HL",
        description: "Grid line elements generated by the given Curtain Grid along the V axis",
        access: GH_ParamAccess.item
        );
      // V grid properties
      manager.AddNumberParameter(
        name: "Horizontal Angle",
        nickname: "HA",
        description: "The angle for the V grid line pattern of the given curtain grid",
        access: GH_ParamAccess.item
        );
      manager.AddParameter(
        param: new Parameters.Param_Enum<Types.CurtainGridAlignType>(),
        name: "Horizontal Justification",
        nickname: "HJ",
        description: "The alignment type for the V grid line pattern of the given curtain grid",
        access: GH_ParamAccess.item
        );
      manager.AddNumberParameter(
        name: "Horizontal Offset",
        nickname: "HO",
        description: "The offset for the V grid line pattern of the given curtain grid",
        access: GH_ParamAccess.item
        );
    }

    protected override void TrySolveInstance(IGH_DataAccess DA)
    {
      // get input
      Types.DataObject<DB.CurtainGrid> dataObj = default;
      if (!DA.GetData("Curtain Grid", ref dataObj))
        return;

      DB.CurtainGrid cgrid = dataObj.Value;

      DA.SetDataList("Cells", cgrid.GetCurtainCells().Select(x => new Types.DataObject<DB.CurtainCell>(x, srcDocument: dataObj.Document)));
      DA.SetDataList("Mullions", cgrid.GetMullionIds().Select(x => Types.Mullion.FromElement(dataObj.Document.GetElement(x))));
      DA.SetDataList("Panels", cgrid.GetPanelIds().Select(x => Types.Element.FromElement(dataObj.Document.GetElement(x))));

      // GetVGridLineIds returns grid lines perpendicular to V
      DA.SetDataList("Vertical Lines", cgrid.GetVGridLineIds().Select(x => Types.CurtainGridLine.FromElement(dataObj.Document.GetElement(x))));
      DA.SetData("Vertical Angle", cgrid.Grid1Angle);
      DA.SetData("Vertical Justification", cgrid.Grid1Justification);
      DA.SetData("Vertical Offset", cgrid.Grid1Offset * Revit.ModelUnits);

      // GetUGridLineIds returns grid lines perpendicular to U
      DA.SetDataList("Horizontal Lines", cgrid.GetUGridLineIds().Select(x => Types.CurtainGridLine.FromElement(dataObj.Document.GetElement(x))));
      DA.SetData("Horizontal Angle", cgrid.Grid2Angle);
      DA.SetData("Horizontal Justification", cgrid.Grid2Justification);
      DA.SetData("Horizontal Offset", cgrid.Grid2Offset * Revit.ModelUnits);
    }
  }
}
